version: '2'
services:
  security:
    build:
      context: .
      dockerfile: security-Dockerfile
    ports:
      - "8080"
    environment:
      - METRICS_REPORTING_DAS_RECEIVERURL=tcp://192.168.1.4:7611
      - HTTP_MONITORING_DAS_RECEIVERURL=tcp://192.168.1.4:7611

  transaction:
    build:
      context: .
      dockerfile: transaction-Dockerfile
    ports:
      - "8080"
    environment:
      - SENTINEL1_HOST=redis-sentinel
      - SENTINEL1_PORT=26379
      - METRICS_REPORTING_DAS_RECEIVERURL=tcp://192.168.1.4:7611
      - HTTP_MONITORING_DAS_RECEIVERURL=tcp://192.168.1.4:7611
    links:
       - sentinel:redis-sentinel

  pet:
    build:
      context: .
      dockerfile: pet-Dockerfile
    ports:
      - "8080"
    environment:
      - SENTINEL1_HOST=sentinel
      - SENTINEL1_PORT=26379
      - SENTINEL2_HOST=sentinel
      - SENTINEL2_PORT=26379
      - METRICS_REPORTING_DAS_RECEIVERURL=tcp://192.168.1.4:7611
      - HTTP_MONITORING_DAS_RECEIVERURL=tcp://192.168.1.4:7611
    links:
      - sentinel:redis-sentinel

  fileserver:
    build:
      context: .
      dockerfile: fileserver-Dockerfile
    ports:
      - "31111:8080"
    environment:
      - METRICS_REPORTING_DAS_RECEIVERURL=tcp://192.168.1.4:7611
      - HTTP_MONITORING_DAS_RECEIVERURL=tcp://192.168.1.4:7611

  admin-fe:
    build:
      context: .
      dockerfile: admin-fe-Dockerfile
    ports:
      - "32080:80"
    environment:
      - FE_FILE_SERVICE_HOST=fileserver
      - FE_FILE_SERVICE_PORT=8080
      - PET_SERVICE_HOST=pet
      - PET_SERVICE_PORT=8080
      - SECURITY_SERVICE_HOST=security
      - SECURITY_SERVICE_PORT=8080
      - FE_FILE_SERVICE_NODE_PORT=31111
    links:
      - pet:pet
      - security:security
      - fileserver:fileserver

  store-fe:
    build:
      context: .
      dockerfile: store-fe-Dockerfile
    ports:
      - "32081:81"
    environment:
      - FE_FILE_SERVICE_HOST=fileserver
      - FE_FILE_SERVICE_PORT=8080
      - PET_SERVICE_HOST=pet
      - PET_SERVICE_PORT=8080
      - SECURITY_SERVICE_HOST=security
      - SECURITY_SERVICE_PORT=8080
      - TXN_SERVICE_HOST=transaction
      - TXN_SERVICE_PORT=8080
      - FE_FILE_SERVICE_NODE_PORT=31111
    links:
      - pet:pet
      - security:security
      - transaction:transaction
      - fileserver:fileserver

  master:
    image: redis:3
  slave:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master
  sentinel:
    build:
      context: .
      dockerfile: redis-sentinel-Dockerfile
    ports:
      - "26379"
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - slave

volumes:
  logvolume01: {}
