version: '2'
services:
  security:
    build:
      context: .
      dockerfile: security/Dockerfile
    ports:
      - "8080"
    environment:
      - METRICS_REPORTING_DAS_RECEIVERURL=tcp://10.100.1.192:7611
      - HTTP_MONITORING_DAS_RECEIVERURL=tcp://10.100.1.192:7611

  transaction:
    build:
      context: .
      dockerfile: transaction-Dockerfile
    ports:
      - "8080"
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PORT=6379
      - METRICS_REPORTING_DAS_RECEIVERURL=tcp://10.100.1.192:7611
      - HTTP_MONITORING_DAS_RECEIVERURL=tcp://10.100.1.192:7611
    depends_on:
       - redis

  pet:
    build:
      context: .
      dockerfile: pet/Dockerfile
    ports:
      - "8080"
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PORT=6379
      - METRICS_REPORTING_DAS_RECEIVERURL=tcp://10.100.1.192:7611
      - HTTP_MONITORING_DAS_RECEIVERURL=tcp://10.100.1.192:7611
    depends_on:
      - redis

  fileserver:
    build:
      context: .
      dockerfile: fileserver/Dockerfile
    ports:
      - "31111:8080"
    environment:
      - METRICS_REPORTING_DAS_RECEIVERURL=tcp://10.100.1.192:7611
      - HTTP_MONITORING_DAS_RECEIVERURL=tcp://10.100.1.192:7611

  admin-fe:
    build:
      context: .
      dockerfile: admin-fe/Dockerfile
    ports:
      - "32080:80"
    environment:
      - FE_FILE_SERVICE_HOST=fileserver
      - FE_FILE_SERVICE_PORT=8080
      - PET_SERVICE_HOST=pet
      - PET_SERVICE_PORT=8080
      - SECURITY_SERVICE_HOST=security
      - SECURITY_SERVICE_PORT=8080
      - FE_FILE_SERVICE_NODE_PORT=31111
    links:
      - pet:pet
      - security:security
      - fileserver:fileserver

  store-fe:
    build:
      context: .
      dockerfile: store-fe/Dockerfile
    ports:
      - "32081:81"
    environment:
      - FE_FILE_SERVICE_HOST=fileserver
      - FE_FILE_SERVICE_PORT=8080
      - PET_SERVICE_HOST=pet
      - PET_SERVICE_PORT=8080
      - SECURITY_SERVICE_HOST=security
      - SECURITY_SERVICE_PORT=8080
      - TXN_SERVICE_HOST=transaction
      - TXN_SERVICE_PORT=8080
      - FE_FILE_SERVICE_NODE_PORT=31111

  redis:
    image: redis:3
    ports:
      - "36379:6379"

volumes:
  logvolume01: {}
