version: '2'
services:
  security:
    build:
      context: .
      dockerfile: security-Dockerfile
    ports:
      - "8080"

  transaction:
    build:
      context: .
      dockerfile: transaction-Dockerfile
    ports:
      - "8080"
    environment:
      - SENTINEL1_HOST=redis-sentinel
      - SENTINEL1_PORT=26379

  pet:
    build:
      context: .
      dockerfile: pet-Dockerfile
    ports:
      - "8080"
    environment:
      - SENTINEL1_HOST=redis-sentinel
      - SENTINEL1_PORT=26379

  fileserver:
    build:
      context: .
      dockerfile: fileserver-Dockerfile
    ports:
      - "31111:8080"

    # TODO: volume mounts

  admin-fe:
    build:
      context: .
      dockerfile: admin-fe-Dockerfile
    ports:
      - "80"
    environment:
      - FE_FILE_SERVICE_HOST=fileserver
      - FE_FILE_SERVICE_PORT=80
      - FE_PET_SERVICE_HOST=pet
      - FE_PET_SERVICE_PORT=80
      - FE_USER_SERVICE_HOST=security
      - FE_USER_SERVICE_HOST=80
      - FE_FILE_SERVICE_NODE_PORT=31111

  store-fe:
    build:
      context: .
      dockerfile: store-fe-Dockerfile
    ports:
      - "80"
    environment:
      - FE_FILE_SERVICE_HOST=fileserver
      - FE_FILE_SERVICE_PORT=80
      - FE_PET_SERVICE_HOST=pet
      - FE_PET_SERVICE_PORT=80
      - FE_USER_SERVICE_HOST=security
      - FE_USER_SERVICE_PORT=80
      - FE_TXN_SERVICE_HOST=transaction
      - FE_TXN_SERVICE_PORT=80
      - FE_FILE_SERVICE_NODE_PORT=31111
  redis-sentinel:
     image: kubernetes/redis:v1
     ports:
      - "26379"
     environment:
      - SENTINEL=true
  redis:
    image: kubernetes/redis:v1

    # TODO: volume mounts
volumes:
  logvolume01: {}
